// data.jsx — товары, категории, заказы

const CATEGORIES = [
  { id: 'all',     label: 'Всё',           hint: 'Полный каталог' },
  { id: 'apparel', label: 'Одежда',        hint: 'Худи, толстовки, футболки' },
  { id: 'bags',    label: 'Сумки',         hint: 'Рюкзаки, шопперы, поясные' },
  { id: 'paper',   label: 'Канцелярия',    hint: 'Блокноты, стикеры, ручки' },
  { id: 'gift',    label: 'Welcome-pack',  hint: 'Подарочные наборы новичкам' },
];

const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

// Placeholder products. art = декларативный CSS-арт паттерн для placeholder-изображения.
const PRODUCTS = [
  {
    id: 'hoodie-team',
    name: 'Худи «Команда»',
    cat: 'apparel',
    kind: 'Худи',
    desc: 'Плотный хлопок 320 г/м², свободный крой, унисекс. Принт на спине — нашивка с названием команды.',
    sizes: SIZES,
    colors: [
      { id: 'graphite', label: 'Графит',  swatch: '#3a3a3c' },
      { id: 'cream',    label: 'Кремовый', swatch: '#ece4d2' },
      { id: 'rust',     label: 'Терракот', swatch: '#c97a4f' },
    ],
    art: 'hoodie',
    bg: 'oklch(0.92 0.04 295)',
    weight: 1,
    badge: 'Хит сезона',
    stock: 'В наличии',
  },
  {
    id: 'hoodie-zip',
    name: 'Толстовка на молнии',
    cat: 'apparel',
    kind: 'Худи',
    desc: 'Зип-худи с двумя боковыми карманами. Плотная резинка по низу и рукавам.',
    sizes: SIZES,
    colors: [
      { id: 'black',    label: 'Чёрный', swatch: '#1c1c1e' },
      { id: 'sage',     label: 'Шалфей', swatch: '#9bab94' },
    ],
    art: 'zip',
    bg: 'oklch(0.94 0.03 320)',
    weight: 1,
    stock: 'В наличии',
  },
  {
    id: 'tee-base',
    name: 'Футболка базовая',
    cat: 'apparel',
    kind: 'Футболка',
    desc: 'Хлопок 180 г/м², прямой крой. Маленький вышитый логотип на груди.',
    sizes: SIZES,
    colors: [
      { id: 'white', label: 'Белый',   swatch: '#fafaf7' },
      { id: 'black', label: 'Чёрный',  swatch: '#1c1c1e' },
      { id: 'cream', label: 'Кремовый',swatch: '#ece4d2' },
      { id: 'sage',  label: 'Шалфей',  swatch: '#9bab94' },
    ],
    art: 'tee',
    bg: 'oklch(0.95 0.02 280)',
    weight: 1,
    stock: 'В наличии',
  },
  {
    id: 'tee-2026',
    name: 'Футболка «2026»',
    cat: 'apparel',
    kind: 'Футболка',
    desc: 'Принт на груди — год выпуска. Лимитированная серия к ежегодной встрече.',
    sizes: SIZES,
    colors: [
      { id: 'cream', label: 'Кремовый', swatch: '#ece4d2' },
      { id: 'rust',  label: 'Терракот', swatch: '#c97a4f' },
    ],
    art: 'tee-print',
    bg: '#7000FF',
    fg: '#ffffff',
    weight: 1,
    badge: 'Лимит. серия',
    stock: 'Осталось мало',
  },
  {
    id: 'longsleeve',
    name: 'Лонгслив',
    cat: 'apparel',
    kind: 'Футболка',
    desc: 'Лонгслив из плотного хлопка. Минималистичный принт на рукаве.',
    sizes: SIZES,
    colors: [
      { id: 'black', label: 'Чёрный', swatch: '#1c1c1e' },
      { id: 'cream', label: 'Кремовый', swatch: '#ece4d2' },
    ],
    art: 'long',
    bg: 'oklch(0.94 0.015 295)',
    weight: 1,
    stock: 'В наличии',
  },
  {
    id: 'crew',
    name: 'Свитшот',
    cat: 'apparel',
    kind: 'Худи',
    desc: 'Классический свитшот без капюшона. Тёплый начёс изнутри.',
    sizes: SIZES,
    colors: [
      { id: 'graphite', label: 'Графит',  swatch: '#3a3a3c' },
      { id: 'sage',     label: 'Шалфей',  swatch: '#9bab94' },
    ],
    art: 'crew',
    bg: '#ffe2f3',
    weight: 1,
    stock: 'В наличии',
  },
  {
    id: 'backpack',
    name: 'Рюкзак city',
    cat: 'bags',
    kind: 'Рюкзак',
    desc: 'Городской рюкзак на 18 л. Отделение для ноутбука 15", водоотталкивающая ткань.',
    sizes: ['Один размер'],
    colors: [
      { id: 'graphite', label: 'Графит', swatch: '#3a3a3c' },
      { id: 'sand',     label: 'Песок',  swatch: '#c9b89a' },
    ],
    art: 'backpack',
    bg: 'oklch(0.94 0.025 295)',
    weight: 2,
    badge: 'Новинка',
    stock: 'В наличии',
  },
  {
    id: 'tote',
    name: 'Сумка-шоппер',
    cat: 'bags',
    kind: 'Сумка',
    desc: 'Плотная парусина, длинные ручки. На дне — пришитая бирка с номером партии.',
    sizes: ['Один размер'],
    colors: [
      { id: 'natural', label: 'Натуральный', swatch: '#ddc9a3' },
      { id: 'black',   label: 'Чёрный',      swatch: '#1c1c1e' },
    ],
    art: 'tote',
    bg: 'oklch(0.95 0.03 75)',
    weight: 1,
    stock: 'В наличии',
  },
  {
    id: 'waist',
    name: 'Поясная сумка',
    cat: 'bags',
    kind: 'Сумка',
    desc: 'Компактная поясная сумка с регулируемым ремнём. Три отделения на молнии.',
    sizes: ['Один размер'],
    colors: [
      { id: 'graphite', label: 'Графит', swatch: '#3a3a3c' },
      { id: 'rust',     label: 'Терракот', swatch: '#c97a4f' },
    ],
    art: 'waist',
    bg: '#ffeaf6',
    weight: 1,
    stock: 'В наличии',
  },
  {
    id: 'sticker-pack',
    name: 'Стикерпак',
    cat: 'paper',
    kind: 'Стикеры',
    desc: 'Набор из 12 виниловых стикеров на ноутбук. Виниловое покрытие, не выгорает на солнце.',
    sizes: ['Набор'],
    colors: [{ id: 'mix', label: 'Микс', swatch: '#c97a4f' }],
    art: 'stickers',
    bg: '#f1ebff',
    weight: 0,
    stock: 'В наличии',
  },
  {
    id: 'notebook',
    name: 'Блокнот A5',
    cat: 'paper',
    kind: 'Блокнот',
    desc: 'Блокнот A5 в твёрдой обложке. 160 страниц, бумага в точку, ляссе.',
    sizes: ['A5'],
    colors: [
      { id: 'cream',    label: 'Кремовый',swatch: '#ece4d2' },
      { id: 'graphite', label: 'Графит',  swatch: '#3a3a3c' },
    ],
    art: 'notebook',
    bg: 'oklch(0.95 0.012 295)',
    weight: 0,
    stock: 'В наличии',
  },
  {
    id: 'pen',
    name: 'Ручка металлическая',
    cat: 'paper',
    kind: 'Ручка',
    desc: 'Металлический корпус, гравировка с логотипом, чёрная гелевая паста 0.5 мм.',
    sizes: ['Стандарт'],
    colors: [
      { id: 'silver', label: 'Серебро', swatch: '#c8c8c8' },
      { id: 'black',  label: 'Чёрный',  swatch: '#1c1c1e' },
    ],
    art: 'pen',
    bg: 'oklch(0.94 0.005 295)',
    weight: 0,
    stock: 'В наличии',
  },
  {
    id: 'welcome',
    name: 'Welcome-pack',
    cat: 'gift',
    kind: 'Набор',
    desc: 'Стартовый набор для новичка: футболка, шоппер, стикерпак, блокнот и ручка. Упакован в крафтовую коробку.',
    sizes: ['Один размер'],
    colors: [{ id: 'kit', label: 'В наборе', swatch: '#c97a4f' }],
    art: 'welcome',
    bg: '#5000AA',
    fg: '#ffffff',
    weight: 3,
    badge: 'Для новичков',
    stock: 'В наличии',
  },
];

const MOCK_ORDERS = [
  {
    id: 'M-2026-0142',
    placed: '12 мая 2026',
    status: 'В пути',
    statusTone: 'progress',
    eta: 'Прибудет 24 мая',
    delivery: 'Доставка в офис · Москва, Берсеневская',
    items: [
      { id: 'hoodie-team', name: 'Худи «Команда»', variant: 'M · Графит', qty: 1 },
      { id: 'sticker-pack', name: 'Стикерпак', variant: 'Набор', qty: 1 },
    ],
  },
  {
    id: 'M-2026-0098',
    placed: '02 апреля 2026',
    status: 'Доставлено',
    statusTone: 'done',
    eta: 'Получено 9 апреля',
    delivery: 'Самовывоз · Офис Москва',
    items: [
      { id: 'tee-base', name: 'Футболка базовая', variant: 'L · Кремовый', qty: 2 },
    ],
  },
  {
    id: 'M-2025-1430',
    placed: '18 декабря 2025',
    status: 'Доставлено',
    statusTone: 'done',
    eta: 'Получено 25 декабря',
    delivery: 'Доставка в офис · Питер, Аптекарский',
    items: [
      { id: 'crew',     name: 'Свитшот', variant: 'M · Шалфей', qty: 1 },
      { id: 'notebook', name: 'Блокнот A5', variant: 'A5 · Кремовый', qty: 1 },
    ],
  },
];

const USER = {
  name: 'Анна Соколова',
  team: 'Дизайн · продукт',
  office: 'Москва, Берсеневская 6',
  joined: 'июль 2024',
  quotaLargeUsed: 1,
  quotaLargeTotal: 3,   // крупные позиции (худи, рюкзак)
  quotaSmallUsed: 4,
  quotaSmallTotal: 10,  // мелкие (стикеры, блокноты)
};

const OFFICES = [
  { id: 'msk-bers',   label: 'Москва · Берсеневская 6',  hint: 'выдача с 11:00 до 19:00' },
  { id: 'msk-belrus', label: 'Москва · Белорусская',     hint: 'выдача с 10:00 до 20:00' },
  { id: 'spb-apt',    label: 'Санкт-Петербург · Аптекарский', hint: 'выдача по будням' },
  { id: 'nsk-krasn',  label: 'Новосибирск · Красный пр.',hint: 'выдача по будням' },
];

window.MERCH_DATA = { CATEGORIES, SIZES, PRODUCTS, MOCK_ORDERS, USER, OFFICES };
